# Data Loading

This notebook contains the steps for the loading the dataset and gathering info on the dataset.

In [1]:
# Import required libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Locate the CSV whether the notebook is opened from the same folder
# or executed from the ChatGPT working directory.

df = pd.read_csv(r"MonthlyCrimeDashboard_KnifeCrimeData.csv")

# Keep separate copies for raw-data comparison and cleaning.
raw_df = df.copy()
clean_df = df.copy()

In [3]:
# Display the first five rows to inspect the dataset structure.
clean_df.head()

,Month_Year,Area Type,Borough_SNT,Area Name,Area Code,Crime Type,Crime Subtype,Measure,Financial Year,Count,Refresh Date
0,2025-02-01,Safer Neighbourhood Teams,Lambeth Brixton Windrush,Brixton Windrush,E05014098,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
1,2025-12-01,Safer Neighbourhood Teams,Croydon Selhurst,Selhurst,E05011479,Knife Crime,Knife Crime with Injury,Offences,fy25-26,1,2026-08-18
2,2024-01-01,Safer Neighbourhood Teams,Greenwich Abbey Wood,Abbey Wood,E05014072,Knife Crime,Knife Crime with Injury,Offences,fy23-24,2,2026-08-18
3,2024-12-01,Safer Neighbourhood Teams,Croydon West Thornton,West Thornton,E05011488,Knife Crime,Knife Crime with Injury,Offences,fy24-25,2,2026-08-18
4,2023-02-01,Safer Neighbourhood Teams,Waltham Forest Wood Street,Wood Street,E05013903,Knife Crime,Knife Crime with Injury,Offences,fy22-23,6,2026-08-18

In [4]:
# Display the last five rows to inspect the end of the dataset.
clean_df.tail()

,Month_Year,Area Type,Borough_SNT,Area Name,Area Code,Crime Type,Crime Subtype,Measure,Financial Year,Count,Refresh Date
60192,2026-01-01,Borough,Hammersmith and Fulham,Hammersmith and Fulham,E09000013,Knife Crime,Knife Crime with Injury (Personal Robbery),Offences,fy25-26,2,2026-08-18
60193,2023-10-01,Borough (Georgraphy Not Known),N/K (Legacy Only),N/K (Legacy Only),NaN,Knife Crime,Knife Crime with Injury (Personal Robbery),Offences,fy23-24,3,2026-08-18
60194,2022-09-01,Borough,Haringey,Haringey,E09000014,Knife Crime,Knife Crime with Injury (Personal Robbery),Positive Outcomes,fy22-23,2,2026-08-18
60195,2022-08-01,Borough,Brent,Brent,E09000005,Knife Crime,Knife Crime with Injury (Personal Robbery),Positive Outcomes,fy22-23,1,2026-08-18
60196,2026-01-01,Borough,Southwark,Southwark,E09000028,Knife Crime,Knife Crime with Injury (Personal Robbery),Positive Outcomes,fy25-26,1,2026-08-18

In [5]:
# Check the number of rows and columns.
clean_df.shape

(60197, 11)

In [6]:
clean_df.columns

Index(['Month_Year', 'Area Type', 'Borough_SNT', 'Area Name', 'Area Code',
       'Crime Type', 'Crime Subtype', 'Measure', 'Financial Year', 'Count',
       'Refresh Date'],
      dtype='str')

In [7]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60197 entries, 0 to 60196
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Month_Year      60197 non-null  str
 1   Area Type       60197 non-null  str
 2   Borough_SNT     59954 non-null  str
 3   Area Name       59954 non-null  str
 4   Area Code       59921 non-null  str
 5   Crime Type      60197 non-null  str
 6   Crime Subtype   60197 non-null  str
 7   Measure         60197 non-null  str
 8   Financial Year  60197 non-null  str
 9   Count           60197 non-null  int64
 10  Refresh Date    60197 non-null  str
dtypes: int64(1), str(10)
memory usage: 12.6 MB

In [8]:
clean_df.isnull().sum()

Month_Year          0
Area Type           0
Borough_SNT       243
Area Name         243
Area Code         276
Crime Type          0
Crime Subtype       0
Measure             0
Financial Year      0
Count               0
Refresh Date        0
dtype: int64

In [9]:
clean_df.duplicated().sum()

np.int64(97)

In [10]:
clean_df.describe()

              Count
count  60197.000000
mean       3.199096
std        6.956216
min        1.000000
25%        1.000000
50%        1.000000
75%        3.000000
max      110.000000